name = "MemoryAccesses"
uuid = "2b4af7f8-6b81-4b76-bddc-2206fdd79ed1"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0-DEV"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
julia = "1.6"
